# Generated by Django 5.0.4 on 2024-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='verified_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_phone',
            field=models.BooleanField(default=False),
        ),
    ]
