# Generated by Django 5.0.5 on 2024-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_address_address_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
