# Generated by Django 5.0.5 on 2024-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(related_name='user_badges', through='pages.User_Badge', to='pages.badge'),
        ),
    ]
