# Generated by Django 5.0.4 on 2024-05-14 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_user_comment_count_user_polls_answered_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='pages.user'),
        ),
    ]
