# Generated by Django 5.0.4 on 2024-05-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_comment'),
        ('pages', '0008_user_account_created_user_invited_by'),
    ]

    operations = [
    ]
