# Generated by Django 5.0.4 on 2024-05-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_merge_20240514_1118'),
        ('pages', '0009_merge_20240514_1138'),
    ]

    operations = [
    ]
