# Generated by Django 5.0.4 on 2024-05-16 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_merge_20240514_1118"),
        ("pages", "0009_merge_20240514_1138"),
    ]

    operations = []
