# Generated by Django 5.0.4 on 2024-05-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_merge_20240514_1511'),
        ('pages', '0010_merge_20240515_2333'),
    ]

    operations = [
    ]
