# Generated by Django 5.0.4 on 2024-05-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_merge_20240517_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_list',
            field=models.ManyToManyField(related_name='users', to='pages.comment'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(related_name='posts', to='pages.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='posts_list',
            field=models.ManyToManyField(related_name='users', to='pages.post'),
        ),
    ]
