# Generated by Django 5.0.4 on 2024-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_address_address_type_address_apt_suite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_badge',
            name='granted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
