# Generated by Django 5.0.5 on 2024-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_address_address_type_address_apt_suite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='ownership_type',
            new_name='ownershipType',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='primary_address',
            new_name='primaryAddress',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='property_type',
            new_name='propertyType',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='apt_suite',
            new_name='suite',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Canada', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Vancouver', max_length=127),
            preserve_default=False,
        ),
    ]
