# Generated by Django 5.0.4 on 2024-05-21 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_alter_user_badge_granted_date"),
        ("pages", "0015_rename_ownership_type_address_ownershiptype_and_more"),
    ]

    operations = []
