# Generated by Django 5.0.4 on 2024-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_merge_20240521_1617"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="upvotes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="upvotes",
        ),
        migrations.AddField(
            model_name="comment",
            name="downvoted_by",
            field=models.ManyToManyField(
                blank=True, related_name="downvoted_comments", to="pages.user"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="upvoted_by",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_comments", to="pages.user"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="downvoted_by",
            field=models.ManyToManyField(
                blank=True, related_name="downvoted_posts", to="pages.user"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="upvoted_by",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_posts", to="pages.user"
            ),
        ),
    ]
