# Generated by Django 5.0.5 on 2024-05-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_post_downvotes_alter_post_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postalCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
