# Generated by Django 5.0.5 on 2024-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_comment_downvotes_remove_comment_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_streak_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
