# Generated by Django 5.0.5 on 2024-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_address_postalcode_alter_post_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
